// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Octokit")]
[assembly: AssemblyVersionAttribute("0.29.0")]
[assembly: AssemblyFileVersionAttribute("0.29.0")]
[assembly: AssemblyInformationalVersionAttribute("0.29.0")]
[assembly: ComVisibleAttribute(false)]
namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string Version = "0.29.0";
        internal const string InformationalVersion = "0.29.0";
    }
}
